# Generated by Django 3.2.15 on 2022-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='released_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
