# Generated by Django 3.2.15 on 2022-08-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandises', '0002_auto_20220824_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
