# Generated by Django 3.2 on 2022-08-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandises', '0003_merchandise_is_submitted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='merchcontent',
            constraint=models.UniqueConstraint(fields=('merchendise', 'language'), name='unique_content_for_each_lang'),
        ),
    ]
