# Generated by Django 3.2.15 on 2022-08-29 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchandises', '0005_remove_merchcontent_unique_content_for_each_lang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('language', models.CharField(choices=[('ko', 'Korean'), ('en', 'English'), ('zh', 'Chinese')], default='Korean', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_list', to='merchandises.merchandise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('merchandise', 'user'), name='unique_purchase_for_same_merchandise'),
        ),
    ]
